x64:
  firstOrDefaultFilePatterns:
    - '!build{,/**/*}'
    - '!dist{,/**/*}'
    - build/**/*
    - package.json
    - '!**/node_modules/**'
    - node_modules/**/*
    - '!node_modules/wrangler/**'
    - '!node_modules/miniflare/**'
    - '!node_modules/workerd/**'
    - '!node_modules/@cloudflare/**'
    - '!node_modules/typescript/**'
    - '!node_modules/prettier/**'
    - '!node_modules/vitest/**'
    - '!node_modules/@vitest/**'
    - '!node_modules/eslint/**'
    - '!node_modules/eslint-*/**'
    - '!node_modules/@eslint/**'
    - '!node_modules/playwright/**'
    - '!node_modules/playwright-core/**'
    - '!node_modules/@playwright/**'
    - '!node_modules/electron-builder/**'
    - '!node_modules/app-builder-bin/**'
    - '!node_modules/app-builder-lib/**'
    - '!node_modules/@electron/rebuild/**'
    - '!node_modules/@remix-run/dev/**'
    - '!node_modules/vite/**'
    - '!node_modules/rollup/**'
    - '!node_modules/esbuild/**'
    - '!node_modules/@esbuild/**'
    - '!node_modules/@types/**'
    - '!node_modules/sass/**'
    - '!node_modules/sass-embedded/**'
    - '!node_modules/sass-embedded-*/**'
    - icons/**
    - electron-update.yml
    - '!**/*.{iml,hprof,orig,pyc,pyo,rbc,swp,csproj,sln,suo,xproj,cc,d.ts,mk,a,o,obj,forge-meta,pdb}'
    - '!**/._*'
    - '!**/electron-builder.{yaml,yml,json,json5,toml,ts}'
    - '!**/{.git,.hg,.svn,CVS,RCS,SCCS,__pycache__,.DS_Store,thumbs.db,.gitignore,.gitkeep,.gitattributes,.npmignore,.idea,.vs,.flowconfig,.jshintrc,.eslintrc,.circleci,.yarn-integrity,.yarn-metadata.json,yarn-error.log,yarn.lock,package-lock.json,npm-debug.log,pnpm-lock.yaml,appveyor.yml,.travis.yml,circle.yml,.nyc_output,.husky,.github,electron-builder.env}'
    - '!.yarn{,/**/*}'
    - '!.editorconfig'
    - '!.yarnrc.yml'
  nodeModuleFilePatterns:
    - '**/*'
    - build/**/*
    - package.json
    - node_modules/**/*
    - '!node_modules/wrangler/**'
    - '!node_modules/miniflare/**'
    - '!node_modules/workerd/**'
    - '!node_modules/@cloudflare/**'
    - '!node_modules/typescript/**'
    - '!node_modules/prettier/**'
    - '!node_modules/vitest/**'
    - '!node_modules/@vitest/**'
    - '!node_modules/eslint/**'
    - '!node_modules/eslint-*/**'
    - '!node_modules/@eslint/**'
    - '!node_modules/playwright/**'
    - '!node_modules/playwright-core/**'
    - '!node_modules/@playwright/**'
    - '!node_modules/electron-builder/**'
    - '!node_modules/app-builder-bin/**'
    - '!node_modules/app-builder-lib/**'
    - '!node_modules/@electron/rebuild/**'
    - '!node_modules/@remix-run/dev/**'
    - '!node_modules/vite/**'
    - '!node_modules/rollup/**'
    - '!node_modules/esbuild/**'
    - '!node_modules/@esbuild/**'
    - '!node_modules/@types/**'
    - '!node_modules/sass/**'
    - '!node_modules/sass-embedded/**'
    - '!node_modules/sass-embedded-*/**'
    - icons/**
    - electron-update.yml
